controller_list:
  - name: v1/left_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - LeftShoulderExtensor
      - LeftShoulderAdductor
      - LeftShoulderSupinator
      - LeftElbowExtensor
      - LeftForearmSupinator
      - LeftWristExtensor
      - LeftWrist
  - name: v1/right_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - RightShoulderExtensor
      - RightShoulderAdductor
      - RightShoulderSupinator
      - RightElbowExtensor
      - RightForearmSupinator
      - RightWristExtensor
      - RightWrist
  - name: v1/left_leg_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - LeftHipRotator
      - LeftHipAdductor
      - LeftHipExtensor
      - LeftKneeExtensor
      - LeftAnkleExtensor
      - LeftAnkle
  - name: v1/right_leg_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - RightHipRotator
      - RightHipAdductor
      - RightHipExtensor
      - RightKneeExtensor
      - RightAnkleExtensor
      - RightAnkle
  - name: v1/neck_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - LowerNeckExtensor
      - NeckRotator
      - UpperNeckExtensor
  - name: v1/left_hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - LeftThumbMPYaw
      - LeftThumbMPExtensor
      - LeftThumbPIPExtensor
      - LeftThumbDIPExtensor
      - LeftPrimaryMPYaw
      - LeftPrimaryMPExtensor
      - LeftPrimaryPIPExtensor
      - LeftPrimaryDIPExtensor
      - LeftMiddleMPExtensor
      - LeftMiddlePIPExtensor
      - LeftMiddleDIPExtensor
      - LeftLittleMPYaw
      - LeftLittleMPExtensor
      - LeftLittlePIPExtensor
      - LeftLittleDIPExtensor
  - name: v1/right_hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - RightThumbMPYaw
      - RightThumbMPExtensor
      - RightThumbPIPExtensor
      - RightThumbDIPExtensor
      - RightPrimaryMPYaw
      - RightPrimaryMPExtensor
      - RightPrimaryPIPExtensor
      - RightPrimaryDIPExtensor
      - RightMiddleMPExtensor
      - RightMiddlePIPExtensor
      - RightMiddleDIPExtensor
      - RightLittleMPYaw
      - RightLittleMPExtensor
      - RightLittlePIPExtensor
      - RightLittleDIPExtensor